apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app
  labels:
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
  template:
    metadata:
      labels:
        app: voting-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: location
                operator: In
                values:
                  - public
      containers:
      - name: voting-app
        image: trial1e0fhi.jfrog.io/docker-local/vote-app:5f11548fea5a22287a4ef70ad585b8e34ee07783
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: voting-app-config
---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
spec:
  type: NodePort
  selector:
    app: voting-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007
