name: CD - Update K8s Manifest with New Image Tag

on:
  repository_dispatch:
    types: [deploy-trigger]

permissions:
  contents: write  # Required to push commits

jobs:
  update-manifest:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: vote-app
      IMAGE_TAG: ${{ github.event.client_payload.image_tag }}

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Ensure branch is 'dev'
        run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          if [ "$BRANCH" != "dev" ]; then
            echo "Not on dev branch. Exiting."
            exit 1
          fi

      - name: Update image tag in manifest
        run: |
          echo "Updating image tag to $IMAGE_TAG"
          sed -i "s|image:.*|image: trial1e0fhi.jfrog.io/docker-local/vote-app:${IMAGE_TAG}|" k8s-manifests/flask-vote.yaml

      - name: Configure Git
        run: |
          git config user.name "suchithra05"
          git config user.email "suchithraee1999@gmail.com"

      - name: Commit and push if changes exist
        run: |
          git add k8s-manifests/flask-vote.yaml
          git diff --cached --quiet || git commit -m "Update image tag to $IMAGE_TAG"
          git push origin dev
